--- 
abstract: String localization (L10N) taglib for AxKit
author: 
  - Christopher H. Laco
distribution_type: module
generated_by: Module::Install version 0.68
license: artistic
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: AxKit-XSP-L10N
no_index: 
  directory: 
    - inc
    - t
requires: 
  AxKit: 1.61
  Locale::Maketext: 1.08
  mod_perl: 0
  perl: 5.8.0
tests: t/*.t
version: 0.05000
